In [2]:
import numpy as np

In [4]:
np.zeros((1,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
x.shape

(40,)

In [7]:
x.dtype

dtype('int32')

In [8]:
np.__version__,np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


('1.19.4', None)

In [9]:
x.ndim

1

In [10]:
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
x=np.array([1,2,3,4,5])
np.flip(x)

array([5, 4, 3, 2, 1])

In [67]:
np.array([int(x==4) for x in range(10)])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
x=np.array([1,2,3,4,5])
x.astype(float)

array([1., 2., 3., 4., 5.])

In [22]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [23]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

In [68]:
x=np.arange(10)
np.where(x%2!=0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [69]:
x=np.arange(10)
x[np.where(x%2!=0)]=-1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [70]:
x=np.arange(10)
x[5:9]=12
x

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [35]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [3]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0][::]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
x=np.arange(10)
z=x.reshape((2,5))
z[0]

array([0, 1, 2, 3, 4])

In [4]:
x=np.arange(10)
z=x.reshape((2,5))
z[1]

array([5, 6, 7, 8, 9])

In [45]:
x=np.arange(10)
z=x.reshape((2,5))
q=np.split(z,[2,3],axis=1)
q[1]

array([[2],
       [7]])

In [51]:
x=np.random.random((10,10))
xmin=x.min()
xmax=x.max()
xmin,xmax




(0.009270519389434684, 0.9975709034816597)

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [11]:

c = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
d= np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
list2=[]
list3=[]
for i in range(0,10):
     for j in range(0,10):

        if (c[i]==d[j]):
            list2.append(i)
            list3.append(j)
            break
if(len(list2) ==0):
    print("not found")
print(list2,list3)

[1, 3, 5, 7] [1, 1, 5, 5]


In [14]:
import random
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randint(7,size=random.randrange(1,10))
print(np.where(names[data]!="Will"))

[1 4 4 1 4 4 3 2]
(array([0, 3, 6], dtype=int64),)


In [15]:
data = np.random.randint(7,size=random.randrange(1,10))
print(data)
print(np.where((names[data]!="Will") & (names[data]!="Joe")))

[4 1 5 4]
(array([], dtype=int64),)


In [55]:
np.random.uniform(1,15,size=(5,3))

array([[ 8.81500888,  8.47559362,  6.28010894],
       [ 9.62747837,  5.37320823,  4.65508951],
       [ 2.02434598, 12.09384208,  1.64294657],
       [14.44604006,  1.86386872,  8.82445427],
       [10.69165769, 12.7378057 ,  7.16477159]])

In [8]:
arr=np.random.uniform(1,16,size=(2,2,3))
arr

array([[[ 2.59944272, 13.19840085,  3.92500814],
        [ 8.33189423,  6.95775132,  4.99462772]],

       [[ 6.77241672,  4.97090206, 11.45644322],
        [14.72787659, 12.41071879, 15.63565402]]])

In [9]:
np.swapaxes(arr,0,1)


array([[[ 2.59944272, 13.19840085,  3.92500814],
        [ 6.77241672,  4.97090206, 11.45644322]],

       [[ 8.33189423,  6.95775132,  4.99462772],
        [14.72787659, 12.41071879, 15.63565402]]])

In [59]:
x=np.random.random(size=10)
for i in range(len(x)):
    if x[i]>0.5:
        x[i]=np.sqrt(x[i])
    else:
        x[i]=0
x


array([0.        , 0.        , 0.8950388 , 0.96541696, 0.        ,
       0.        , 0.        , 0.77110188, 0.93258949, 0.        ])

In [58]:
x=np.random.randint(1,100,size=12)
y=np.random.randint(1,100,size=12)
np.maximum(x,y)

array([91, 85, 93, 86, 34, 42, 61, 36, 74, 83, 62, 86])

In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniq=np.unique(names)
np.sort(uniq)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [61]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
inter=np.intersect1d(a,b)
inde=np.where(a==inter)
rem=np.delete(a,inde)
rem

array([1, 2, 3, 4])

In [62]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
row_to_col=np.swapaxes(newColumn,0,1)
sampleArray[:,1:2]=row_to_col
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [63]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [64]:
x=np.random.randint(0,100,size=20)
np.cumsum(x)

array([  69,  117,  127,  143,  233,  243,  329,  393,  463,  547,  553,
        585,  671,  769,  822,  906, 1004, 1010, 1108, 1113], dtype=int32)